piequiz/piequiz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps import FlatPageSitemap
from viridis.sitemaps import TestSitemap, QuestionSitemap
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
    'test': TestSitemap,
    'question': QuestionSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'piequiz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^reset/', include('password_reset.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('django.contrib.auth.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('viridis.urls', namespace="viridis")),
    url(r'^blog/', include('cms.urls')),
    url(r'^blog/sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

piequiz/viridis/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.forms import SetPasswordForm
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from viridis.views import VoteFormView, PopularTestListView, RecentTestListView
from viridis.models import Test
from viridis import views

urlpatterns = patterns('',
    url(r'^$', PopularTestListView.as_view( model=Test, paginate_by=10 ), name='home'),
    url(r'^recently-added/$', RecentTestListView.as_view( model=Test, paginate_by=10 ), name='recent'),
    url(r'^(?P<test_id>\d+)/(?P<slug>[\w-]+)/results/$', views.results, name='results'),
    url(r'^(?P<test_id>\d+)/answer/$', views.answer, name='answer'),
    url(r'^question/(?P<question_id>\d+)/answer/$', views.question_answer, name='question_answer'),
    url(r'^quiz/new$', views.add_test, name='add_test'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/tests/$', views.my_tests, name='my_tests'),
    (r'^search/', include('haystack.urls')),
    (r'^search/autocomplete/', include('haystack.urls')),
    url(r'^vote/$', VoteFormView.as_view(), name="vote"),
    url(r'^(?P<test_id>\d+)/$', RedirectView.as_view(url='slug/')),
    url(r'^questions/add$', views.add_question, name='add_question'),
    url(r'^accounts/password_change/$',
        'django.contrib.auth.views.password_change',
        {'password_change_form': SetPasswordForm},
        name="password_change"),
    url(r'^choices/add$', views.add_choice, name='add_choice'),
    url(r'^(?P<test_id>\d+)/(?P<slug>[\w-]+)/$', views.test, name='test'),
    url(r'^question/(?P<question_id>\d+)/(?P<slug>[\w-]+)/$', views.question, name='question'),
    url(r'^history/$', views.history, name='history'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

piequiz/viridis/models.py
import datetime
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class TestVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(TestVoteCountManager,
self).get_queryset().annotate(
        votes=Count('vote')).order_by('-rank_score', '-votes')

class Test(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200, verbose_name='quiz')
    tag = models.CharField(max_length=10, blank=True, null=True)
    marks = models.IntegerField(default=0)
    marks_per_question = models.IntegerField(default=0)
    slug = models.SlugField(max_length=200)
    rank_score = models.FloatField(default=0.0)
    pub_date = models.DateTimeField('date', auto_now_add=True)
    with_votes = TestVoteCountManager()
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'quizzes'
        verbose_name = 'quiz'

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)

        super(Test, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/%s/%s" % (self.id, self.slug)

    def set_rank(self):
        # Based on HN ranking algo
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.submitted_on
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Question(models.Model):
    question_text = models.CharField(max_length = 1000)
    question_pic = models.ImageField(upload_to='images/', blank=True)
    test = models.ForeignKey(Test)
    slug = models.SlugField(max_length=1000, blank=True, null=True)
    marks = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_date']

    def __unicode__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.question_text)

        super(Question, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/question/%s/%s/" % (self.id, self.slug)

class Choice(models.Model):
    choice_text = models.CharField(max_length=500)
    question = models.ForeignKey(Question)
    test_id = models.IntegerField()
    is_correct = models.NullBooleanField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.id)

class Vote(models.Model):
    voter = models.ForeignKey(User)
    test = models.ForeignKey(Test)

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.test.title)

class History(models.Model):
    user = models.ForeignKey(User)
    test = models.CharField(max_length=200)
    test_id = models.IntegerField()
    score = models.IntegerField()
    marks = models.IntegerField()
    pub_date = models.DateTimeField(auto_now=True)

piequiz/viridis/views.py
import datetime
import simplejson as json
from django_tables2   import RequestConfig
from viridis.tables import TestTable
from django.forms.formsets import formset_factory
from django.forms.models import modelformset_factory
from viridis.forms import AddTestForm, AddQuestionForm, AddChoiceForm, VoteForm
from django.contrib.auth.decorators import login_required, user_passes_test
from haystack.query import SearchQuerySet
from viridis.models import Test, Question, Choice, Vote, History
from itertools import repeat
from django.core import serializers
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict),
content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        test = get_object_or_404(Test, pk=form.data["test"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, test=test)
        has_voted = (len(prev_votes)>0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, test=test)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors}

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

@login_required
def profile(request):
    return render(request, 'viridis/profile.html', {"test": test})

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def my_tests(request):
    test = TestTable(Test.objects.filter(user=request.user.id))
    test.paginate(page=request.GET.get('page', 1), per_page=10)
    # delte selected quizes
    request.POST.get('delete')
    Test.objects.filter(id__in=request.POST.getlist('selection')).delete()
    return render(request, 'viridis/mytests.html', {"test": test})

class PopularTestListView(ListView):
    model = Test
    queryset = Test.with_votes.all()
    popular = 'active'
    def get_context_data(self, **kwargs):
        context = super(PopularTestListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            tests_in_page = [test.id for test in context["object_list"]]
            voted = voted.filter(test_id__in=tests_in_page)
            voted = voted.values_list('test_id', flat=True)
            context['voted'] = voted
        # Change tab class to active in this page. Not very elegant.
        # TODO: Create a more elegant solution.
        context['popular'] = self.popular
        return context

class RecentTestListView(ListView):
    queryset = Test.objects.order_by('-pub_date')
    recent = 'active'
    def get_context_data(self, **kwargs):
        context = super(RecentTestListView, self).get_context_data(**kwargs)
        # Change tab class to active in this page. Not very elegant.
        # TODO: Create a more elegant solution.
        context['recent'] = self.recent
        return context


def test(request, test_id, slug):
    test = get_object_or_404(Test, pk=test_id)
    if not slug == test.slug:
        return HttpResponsePermanentRedirect(test.get_absolute_url())
    return render(request, 'viridis/test.html', {'test': test})

def question(request, question_id, slug):
    question = get_object_or_404(Question, pk=question_id)
    test = question.test.tag
    if not slug == slugify(question.question_text):
        return HttpResponsePermanentRedirect(question.get_absolute_url())
    return render(request, 'viridis/question.html', {'question': question, 'test': test})

def question_answer(request, question_id):
    correct_choice = Choice.objects.get(question=question_id, is_correct=True)
    if request.method == 'POST' and request.is_ajax:
        selected = request.POST.get('choice')
        question = request.POST.get('question_id')

    return HttpResponse(str(correct_choice) == str(selected))

def answer(request, test_id):
    test = Test.objects.get(pk=test_id)
    request.session['choice_id'] = request.POST.getlist('choice')
    request.session['question_id'] = request.POST.getlist('question_id')

    if request.is_ajax(): # I don't know why but it works
        return render(request, 'viridis/test.html', {'test': test})
    else:
        return HttpResponse("Sorry, please enable javascript in your browser to take this test.")


def results(request, test_id, slug):
    test = get_object_or_404(Test, pk=test_id)
    correct_answers = Choice.objects.filter(test_id=test_id, is_correct=True).values_list("id", flat=True)
    y = [unicode(i) for i in correct_answers] # Convert int elements to unicode
    answer_match = set(y).intersection(request.session['choice_id']) # create set
    l_answer_match = list(answer_match) # Convert answer_match to list
    score = len(l_answer_match) * test.marks_per_question # get the total marks of scored by user
    slug = test.slug

    if request.user.is_authenticated():
        try:
            history = History.objects.get(user=request.user, test_id=test.pk)
            history.score = score
            history.save()
        except (ValueError, History.DoesNotExist):
            History.objects.create(user=request.user, test=test.title, test_id=test.pk, score=score, marks=test.marks)
    else:
        pass

    return render(request, 'viridis/results.html',{
        'score': score,
        'percentage_score': int(float(score)/test.marks*100),
        'test': test })

@login_required(login_url = "/accounts/login/")
def history(request):
    return render(request, 'viridis/history.html', {
        'history': History.objects.filter(user=request.user)
        })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required(login_url = "/accounts/login/")
def add_test(request):
    if request.method == "POST":
        form = AddTestForm(request.POST)
        if form.is_valid():
            test = form.save(commit=False)
            cd = form.cleaned_data
            test.user_id = request.user.id
            request.session['no_of_question'] = cd['questions']
            request.session['total_marks'] = cd['marks']
            test.marks_per_question = request.session['total_marks']/request.session['no_of_question']
            test.save()
            request.session['test_title'] = test.title
            request.session['test_id'] = test.pk
            return HttpResponseRedirect('/questions/add')
    else:
        form = AddTestForm(label_suffix='')
    return render(request, 'viridis/new_test.html', {
        "form": form
    })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def add_question(request):
    """User accesses the add_question view.
    If the number of extra forms has been defined by the user, display them.
    Else, display one form.
    """
    try:
        extra_questions = request.session['no_of_question']
        mark_per_question = (request.session['total_marks']/request.session['no_of_question'])
        request.session['mark_per_question'] = mark_per_question
    except KeyError:
        extra_questions = 1
    QuestionFormSet = formset_factory(AddQuestionForm, extra=extra_questions)
    if request.method == "POST":
        formset = QuestionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            for i in range(0, extra_questions):
                question = Question(
                question_text = request.POST.get('form-' + str(i) + '-question_text'),
                question_pic = request.FILES.get('form-' + str(i) + '-image_file'),
                test_id = request.session['test_id'],
                marks = mark_per_question,
                pub_date = datetime.datetime.now(),
                )
                question.save()
            return HttpResponseRedirect('/choices/add')
    else:
        try:
            formset = QuestionFormSet()
        except KeyError:
            formset = QuestionFormSet()
    return render(request, 'viridis/create_questions.html', {
        "formset": formset,
        "title": request.session['test_title']
    })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def add_choice(request):
    """User accesses the add_choice view.
    If the number of extra forms has been defined by the user, display them.
    Else, display one form.
    """
    mark = request.session['mark_per_question']
    test = Test.objects.get(id = request.session['test_id'])
    questions = Question.objects.filter(test_id=test.pk)
    questions_pks = [x.pk for item in questions for x in repeat(item, 4)] # multiply ...
        # pk elements in this list by 4
    try:
        extra_questions = request.session['no_of_question']
    except KeyError:
        extra_questions = 1
    ChoiceFormSet = modelformset_factory(Choice, form=AddChoiceForm, extra=extra_questions*4)
    if request.method == "POST":
        formset = ChoiceFormSet(request.POST)
        if formset.is_valid():
            for i in range(0, extra_questions*4):
                choice = Choice(
                test_id = request.session['test_id'],
                question_id = questions_pks[i],

piequiz/viridis/templates/viridis/create_questions.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}Add Questions{% endblock %}
{% block content %}

{% if form.errors %}
  <p><i class="glyphicon glyphicon-info-sign"></i>Please correct the errors below: {{ form.non_field_errors }}</p>
  {% endif %}
<hr>
<ol class="breadcrumb">
  <li>Quiz</li>
  <li><a href="{% url 'viridis:add_question' %}">Questions</a></li>
  <li>Choices</li>
</ol>

<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title">Add questions to {{ title }}</h3></div>
<div class="panel-body">
  <form id="question-form" method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
    {% bootstrap_formset formset layout='vertical' %}
          {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "arrow-right" %} Continue
            </button>
          {% endbuttons %}

      {{ formset.management_form }}
  </form>
</div>
</div>
{% endblock %}

piequiz/viridis/templates/viridis/profile.html
{% extends "base.html" %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}
<hr>
<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title">{{ user.username }}</h3></div>
  <div class="panel-body">
  {% if user.is_active and user.is_staff %}
      <i class="fa fa-file fa-4x fa-blue"></i>
      <a href="{% url 'viridis:my_tests' %}">My Quizzes</a>
      <hr>
  {% endif %}
      <i class="fa fa-lock fa-4x fa-blue"></i>
      <a href="{% url 'django.contrib.auth.views.password_change' %}">Change password</a>
      <hr>
      <i class="fa fa-folder-open fa-4x fa-blue"></i>
      <a href="{% url 'viridis:history' %}">History</a>
      <hr>
  </div>
</div>
{% endblock %}

piequiz/viridis/templates/viridis/question.html
{% extends "base.html" %}
{% block title %}{{ question.question_text }}{% endblock %}
{% block metadesc %}
  {{ question.question_text }}
{% endblock %}
{% block date_created %}
<hr>
See <a href="{% url 'viridis:history' %}">previous scores</a>.
{% endblock %}
{% block head %}
{% if test == 'maths' %}
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
  </script>
  <script type="text/javascript"
    src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
{% endif %}
{% endblock %}
{% block content %}
<div id="question">
  <p>{{ question.question_text|linebreaksbr }}</p>
  <form class="question-form" action="{% url 'viridis:question_answer' question.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="question_id" value="{{ question.pk }}" />
    {% if question.question_pic %}
    <div class="img-frame">
      <img class="question-img" src="/media/{{ question.question_pic }}" width="95%" alt="">
    </div>
    {% endif %}
    {% for choice in question.choice_set.all %}
      <label for="choice{{ choice.id }}" class="label-choice">{% cycle '(A)' '(B)' '(C)' '(D)' %} <input type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}"/>  {{ choice.choice_text|linebreaksbr }}</label><br />
    {% endfor %}
    <button id="question-submit" class="btn btn-sm btn-primary" type="submit">Submit</button>
  </form>
</div>
{% endblock %}

piequiz/viridis/templates/viridis/results.html
{% extends "base.html" %}
{% block head %}
  <link href="http://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet" type="text/css">
{% if test.tag == 'maths' %}
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
  </script>
  <script type="text/javascript"
    src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
{% endif %}
{% endblock %}
{% block title %}Results for {{ test.title }}{% endblock %}
{% block date_created %}
<hr>
See <a href="{% url 'viridis:history' %}">previous scores</a>.
{% endblock %}
{% block content %}
  <hr>
  <h2>Quiz Results for <u>{{ test.title }}</u></h2>
  <p id="percent-score">
    {{ percentage_score }}%
    <small>
      <p>You scored <span class="badge">{{score}}</span> marks out of <span class="badge">{{ test.marks }}</span></p>
    </small>
  </p>
  <div>
  <em>Correct choices are highlighted below</em>
  <p>
  {% if test.question_set.all %}
    {% for question in test.question_set.all %}
      <p> {{ forloop.counter }}. {{ question.question_text }} </p>
      {% for choice in question.choice_set.all %}
        <p class="{% if choice.is_correct == True %}correct_answer{% endif %}"> {% cycle '(A)' '(B)' '(C)' '(D)' %} {{ choice.choice_text }} </p>
      {% endfor %}
    {% endfor %}
  {% endif %}
  </p>
  </div>
  <p><i class="fa fa-refresh fa-spin fa-green"></i> <a href="{{ test.get_absolute_url }}">Redo</a> the quiz!</p>
{% endblock %}

piequiz/viridis/templates/viridis/test.html
{% extends 'base.html' %}
{% load humanize %}
{% load bootstrap3 %}
{% block metadesc %}
Take the {{ test.title }} paper now for FREE!
{% endblock %}
{% block head %}
{% if test.tag == 'maths' %}
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
  </script>
  <script type="text/javascript"
    src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>
{% endif %}
{% endblock %}
{% block date_created %}
  <hr>
  <p><i class="fa fa-edit fa-2x fa-blue"></i>created <span class="badge">{{ test.pub_date|naturaltime|capfirst }}</span></p>
  <p><i class="fa fa-thumbs-o-up fa-2x fa-green"></i> approved by <span class="badge">{{ test.votes }} pe{{ test.votes|pluralize:"rson,ople" }}</span></p>
{% endblock %}

{% block title %}{{ test.title }}{% endblock %}

{% block content %}
<div class="panel panel-default panel-top">
  <div class="">
    <h1 class="panel-heading bordered-heading" title="{{ test.title }}">{{ test.title|truncatechars:27 }}</h1>
  </div>
  <div class="panel-body test-body">
{% if test.question_set.all %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% for question in test.question_set.all %}
<ul class="list-unstyled">
  <li>{{ forloop.counter }}. <a href="{{ question.get_absolute_url }}">{{ question.question_text|linebreaksbr }}</a> (<em>{{ question.marks }} marks</em>)</li>
    {% if question.question_pic %}
      <div class="img-frame">
        <img class="question-img" src="/media/{{ question.question_pic }}" width="95%" alt="">
      </div>
    {% endif %}
</ul>
<form class="test-form" action="{% url 'viridis:answer' test.id %}" method="post">
{% csrf_token %}
  <input type="hidden" name="question_id" value="{{ question.pk }}" />
  {% for choice in question.choice_set.all %}
    <label for="choice{{ choice.id }}" class="label-choice">{% cycle '(A)' '(B)' '(C)' '(D)' %} <input class="input-choice" type="radio" name="choice" id="choice{{ choice.id }}" value="{{ choice.id }}"/>  {{ choice.choice_text|linebreaksbr }}</label><br />
  {% endfor %}
</form>
<hr>
{% endfor %}
{% else %}
<p>There are no questions for <i>{{ test.title }}</i>.</p>
{% endif %}
    </div>
</div>
  <hr>
<div class="footer-test">
  <div class="footer-wrap">
  <div class="rating">
    <ul class="footer-list">
      <li>
      <form method="post" action="{% url 'viridis:vote' %}" class="vote_form" role="form">
      {% csrf_token %}
        <input type="hidden" id="id_test" name="test" class="hidden_id" value="{{ test.pk }}" />
        <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
        {% if not user.is_authenticated %}
          <button class="btn btn-sm btn-success" title="Please log in to vote"><i class="fa fa-thumbs-o-up"></i></button>
        {% elif test.pk not in voted %}
          <button id="approve" class="btn btn-sm btn-success"><i class="fa fa-thumbs-up"></i></button>
        {% else %}
          <div class="btn-group">
            <button class="btn btn-sm btn-success approve">Upvote</button>
            <button class= "btn btn-sm btn-success" title="Approved by {{ test.votes }} pe{{ test.votes|pluralize:"rson,ople" }}">{{ test.votes }} </button>
          </div>
        {% endif %}
      </form>
      </li>
      <li>
        <a href="{{ test.get_absolute_url }}/results/" class="btn btn-sm btn-primary">
          Finish
        </a>
      </li>
    </ul>
  </div>
  </div>
</div>

{% endblock %}
<div class="footer-remove">
{% block footer %}
{% endblock %}
</div>

piequiz/viridis/templates/viridis/test_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% block metadesc %}
Get multiple-choice KCPE past papers.
{% endblock %}
{% block date_created %}
<hr>
<h2><i id="tags" class="glyphicon glyphicon-tags"></i> Tags</h2>
<p><b><a class="tag" href="javascript:void(0);" value="kiswahili">Kiswahili</a></b><p>
<p><b><a class="tag" href="javascript:void(0);" value="science">Science</a></b></p>
<p><b><a class="tag" href="javascript:void(0);" value="mathematics">Mathematics</a></b></p>
<p><b><a class="tag" href="javascript:void(0);" value="religious education">Religious Education</a></b></p>
<p><b><a class="tag" href="javascript:void(0);" value="social studies">Social Studies</a></b></p>
<p><b><a class="tag" href="javascript:void(0);" value="english">English</a></b></p>
{% endblock %}
{% block content %}
<hr>
<div id="index-div">
  <ul id="index-nav-tabs" class="nav nav-tabs">
    <li role="presentation" class="{{ popular }}">
      <a href="{% url 'viridis:home' %}"><icon class="fa fa-heart"></icon> Popular</a>
    </li>
    <li role="presentation" class="{{ recent }}">
      <a href="{% url 'viridis:recent' %}"><icon class="fa fa-clock-o"></icon> Recent</a>
    </li>
  </ul>
  <div id="index-panel" class="tab-content">
    <div class="tab-pane fade active in">
    {% for test in object_list %}
      <li class="list-unstyled list-border">
        <p>
          <a href="{{ test.get_absolute_url }}">
            <b>{{ test.title|truncatechars:140 }}</b>
          </a>
          created on {{ test.pub_date|date:"M d, Y" }}
        </p>
        <p>
          <span class="badge">
            {{ test.question_set.all|length }} question{{ test.question_set.all|length|pluralize:"s" }}
          </span>
          {% if test.votes %}
          <i class="fa fa-heart"></i>
          {{ test.votes }}
          {% endif %}
        </p>
      </li>
{% empty %}
  <p>Sorry, there are no quizzes available at the moment.</p>
{% endfor %}
{# .... **Pagination section** .... #}
{% if is_paginated %}
  <ul class="pagination pagination-centered">
  {% if page_obj.has_previous %}
    <li><a href="?page=1">&lsaquo;&laquo;</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
  {% endif %}
    {% for i in paginator.page_range %}
    <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;&rsaquo;</a></li>
    {% endif %}
  </ul>
{% endif %}
  </div>
</div>
</div>
{% endblock %}