piequiz/piequiz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.sitemaps.views import sitemap
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps import FlatPageSitemap
from viridis.sitemaps import TestSitemap, QuestionSitemap
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
    'test': TestSitemap,
    'question': QuestionSitemap,
}

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'piequiz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    (r'^reset/', include('password_reset.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'', include('django.contrib.auth.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('viridis.urls', namespace="viridis")),
    url(r'^blog/', include('cms.urls')),
    url(r'^blog/sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
)

piequiz/viridis/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.forms import SetPasswordForm
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from viridis.views import VoteFormView, PopularTestListView, RecentTestListView
from viridis.models import Test
from viridis import views

urlpatterns = patterns('',
    url(r'^$', PopularTestListView.as_view( model=Test, paginate_by=10 ), name='home'),
    url(r'^recently-added/$', RecentTestListView.as_view( model=Test, paginate_by=10 ), name='recent'),
    url(r'^(?P<test_id>\d+)/(?P<slug>[\w-]+)/results/$', views.results, name='results'),
    url(r'^(?P<test_id>\d+)/answer/$', views.answer, name='answer'),
    url(r'^question/(?P<question_id>\d+)/answer/$', views.question_answer, name='question_answer'),
    url(r'^quiz/new$', views.add_test, name='add_test'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/tests/$', views.my_tests, name='my_tests'),
    (r'^search/', include('haystack.urls')),
    (r'^search/autocomplete/', include('haystack.urls')),
    url(r'^vote/$', VoteFormView.as_view(), name="vote"),
    url(r'^(?P<test_id>\d+)/$', RedirectView.as_view(url='slug/')),
    url(r'^questions/add$', views.add_question, name='add_question'),
    url(r'^accounts/password_change/$',
        'django.contrib.auth.views.password_change',
        {'password_change_form': SetPasswordForm},
        name="password_change"),
    url(r'^choices/add$', views.add_choice, name='add_choice'),
    url(r'^(?P<test_id>\d+)/(?P<slug>[\w-]+)/$', views.test, name='test'),
    url(r'^question/(?P<question_id>\d+)/(?P<slug>[\w-]+)/$', views.question, name='question'),
    url(r'^history/$', views.history, name='history'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

piequiz/viridis/models.py
import datetime
from django.db import models
from django.db.models import Count
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class TestVoteCountManager(models.Manager):
    def get_queryset(self):
        return super(TestVoteCountManager,
self).get_queryset().annotate(
        votes=Count('vote')).order_by('-rank_score', '-votes')

class Test(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200, verbose_name='quiz')
    tag = models.CharField(max_length=10, blank=True, null=True)
    marks = models.IntegerField(default=0)
    marks_per_question = models.IntegerField(default=0)
    slug = models.SlugField(max_length=200)
    rank_score = models.FloatField(default=0.0)
    pub_date = models.DateTimeField('date', auto_now_add=True)
    with_votes = TestVoteCountManager()
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'quizzes'
        verbose_name = 'quiz'

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)

        super(Test, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/%s/%s" % (self.id, self.slug)

    def set_rank(self):
        # Based on HN ranking algo
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.submitted_on
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Question(models.Model):
    question_text = models.CharField(max_length = 1000)
    question_pic = models.ImageField(upload_to='images/', blank=True)
    test = models.ForeignKey(Test)
    slug = models.SlugField(max_length=1000, blank=True, null=True)
    marks = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['pub_date']

    def __unicode__(self):
        return self.question_text

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.question_text)

        super(Question, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return "/question/%s/%s/" % (self.id, self.slug)

class Choice(models.Model):
    choice_text = models.CharField(max_length=500)
    question = models.ForeignKey(Question)
    test_id = models.IntegerField()
    is_correct = models.NullBooleanField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.id)

class Vote(models.Model):
    voter = models.ForeignKey(User)
    test = models.ForeignKey(Test)

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.test.title)

class History(models.Model):
    user = models.ForeignKey(User)
    test = models.CharField(max_length=200)
    test_id = models.IntegerField()
    score = models.IntegerField()
    marks = models.IntegerField()
    pub_date = models.DateTimeField(auto_now=True)

piequiz/viridis/views.py
import datetime
import simplejson as json
from django_tables2   import RequestConfig
from viridis.tables import TestTable
from django.forms.formsets import formset_factory
from django.forms.models import modelformset_factory
from viridis.forms import AddTestForm, AddQuestionForm, AddChoiceForm, VoteForm
from django.contrib.auth.decorators import login_required, user_passes_test
from haystack.query import SearchQuerySet
from viridis.models import Test, Question, Choice, Vote, History
from itertools import repeat
from django.core import serializers
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify

class JSONFormMixin(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict),
content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class VoteFormBaseView(FormView):
    form_class = VoteForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        test = get_object_or_404(Test, pk=form.data["test"])
        user = self.request.user
        prev_votes = Vote.objects.filter(voter=user, test=test)
        has_voted = (len(prev_votes)>0)

        ret = {"success": 1}
        if not has_voted:
            # add vote
            v = Vote.objects.create(voter=user, test=test)
            ret["voteobj"] = v.id
        else:
            # delete vote
            prev_votes[0].delete()
            ret["unvoted"] = 1
        return self.create_response(ret, True)

    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors}

class VoteFormView(JSONFormMixin, VoteFormBaseView):
    pass

@login_required
def profile(request):
    return render(request, 'viridis/profile.html', {"test": test})

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def my_tests(request):
    test = TestTable(Test.objects.filter(user=request.user.id))
    test.paginate(page=request.GET.get('page', 1), per_page=10)
    # delte selected quizes
    request.POST.get('delete')
    Test.objects.filter(id__in=request.POST.getlist('selection')).delete()
    return render(request, 'viridis/mytests.html', {"test": test})

class PopularTestListView(ListView):
    model = Test
    queryset = Test.with_votes.all()
    popular = 'active'
    def get_context_data(self, **kwargs):
        context = super(PopularTestListView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            voted = Vote.objects.filter(voter=self.request.user)
            tests_in_page = [test.id for test in context["object_list"]]
            voted = voted.filter(test_id__in=tests_in_page)
            voted = voted.values_list('test_id', flat=True)
            context['voted'] = voted
        # Change tab class to active in this page. Not very elegant.
        # TODO: Create a more elegant solution.
        context['popular'] = self.popular
        return context

class RecentTestListView(ListView):
    queryset = Test.objects.order_by('-pub_date')
    recent = 'active'
    def get_context_data(self, **kwargs):
        context = super(RecentTestListView, self).get_context_data(**kwargs)
        # Change tab class to active in this page. Not very elegant.
        # TODO: Create a more elegant solution.
        context['recent'] = self.recent
        return context


def test(request, test_id, slug):
    test = get_object_or_404(Test, pk=test_id)
    if not slug == test.slug:
        return HttpResponsePermanentRedirect(test.get_absolute_url())
    return render(request, 'viridis/test.html', {'test': test})

def question(request, question_id, slug):
    question = get_object_or_404(Question, pk=question_id)
    test = question.test.tag
    if not slug == slugify(question.question_text):
        return HttpResponsePermanentRedirect(question.get_absolute_url())
    return render(request, 'viridis/question.html', {'question': question, 'test': test})

def question_answer(request, question_id):
    correct_choice = Choice.objects.get(question=question_id, is_correct=True)
    if request.method == 'POST' and request.is_ajax:
        selected = request.POST.get('choice')
        question = request.POST.get('question_id')

    return HttpResponse(str(correct_choice) == str(selected))

def answer(request, test_id):
    test = Test.objects.get(pk=test_id)
    request.session['choice_id'] = request.POST.getlist('choice')
    request.session['question_id'] = request.POST.getlist('question_id')

    if request.is_ajax(): # I don't know why but it works
        return render(request, 'viridis/test.html', {'test': test})
    else:
        return HttpResponse("Sorry, please enable javascript in your browser to take this test.")


def results(request, test_id, slug):
    test = get_object_or_404(Test, pk=test_id)
    correct_answers = Choice.objects.filter(test_id=test_id, is_correct=True).values_list("id", flat=True)
    y = [unicode(i) for i in correct_answers] # Convert int elements to unicode
    answer_match = set(y).intersection(request.session['choice_id']) # create set
    l_answer_match = list(answer_match) # Convert answer_match to list
    score = len(l_answer_match) * test.marks_per_question # get the total marks of scored by user
    slug = test.slug

    if request.user.is_authenticated():
        try:
            history = History.objects.get(user=request.user, test_id=test.pk)
            history.score = score
            history.save()
        except (ValueError, History.DoesNotExist):
            History.objects.create(user=request.user, test=test.title, test_id=test.pk, score=score, marks=test.marks)
    else:
        pass

    return render(request, 'viridis/results.html',{
        'score': score,
        'percentage_score': int(float(score)/test.marks*100),
        'test': test })

@login_required(login_url = "/accounts/login/")
def history(request):
    return render(request, 'viridis/history.html', {
        'history': History.objects.filter(user=request.user)
        })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required(login_url = "/accounts/login/")
def add_test(request):
    if request.method == "POST":
        form = AddTestForm(request.POST)
        if form.is_valid():
            test = form.save(commit=False)
            cd = form.cleaned_data
            test.user_id = request.user.id
            request.session['no_of_question'] = cd['questions']
            request.session['total_marks'] = cd['marks']
            test.marks_per_question = request.session['total_marks']/request.session['no_of_question']
            test.save()
            request.session['test_title'] = test.title
            request.session['test_id'] = test.pk
            return HttpResponseRedirect('/questions/add')
    else:
        form = AddTestForm(label_suffix='')
    return render(request, 'viridis/new_test.html', {
        "form": form
    })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def add_question(request):
    """User accesses the add_question view.
    If the number of extra forms has been defined by the user, display them.
    Else, display one form.
    """
    try:
        extra_questions = request.session['no_of_question']
        mark_per_question = (request.session['total_marks']/request.session['no_of_question'])
        request.session['mark_per_question'] = mark_per_question
    except KeyError:
        extra_questions = 1
    QuestionFormSet = formset_factory(AddQuestionForm, extra=extra_questions)
    if request.method == "POST":
        formset = QuestionFormSet(request.POST, request.FILES)
        if formset.is_valid():
            for i in range(0, extra_questions):
                question = Question(
                question_text = request.POST.get('form-' + str(i) + '-question_text'),
                question_pic = request.FILES.get('form-' + str(i) + '-image_file'),
                test_id = request.session['test_id'],
                marks = mark_per_question,
                pub_date = datetime.datetime.now(),
                )
                question.save()
            return HttpResponseRedirect('/choices/add')
    else:
        try:
            formset = QuestionFormSet()
        except KeyError:
            formset = QuestionFormSet()
    return render(request, 'viridis/create_questions.html', {
        "formset": formset,
        "title": request.session['test_title']
    })

@user_passes_test(lambda u: u.is_staff, login_url='/')
@login_required
def add_choice(request):
    """User accesses the add_choice view.
    If the number of extra forms has been defined by the user, display them.
    Else, display one form.
    """
    mark = request.session['mark_per_question']
    test = Test.objects.get(id = request.session['test_id'])
    questions = Question.objects.filter(test_id=test.pk)
    questions_pks = [x.pk for item in questions for x in repeat(item, 4)] # multiply ...
        # pk elements in this list by 4
    try:
        extra_questions = request.session['no_of_question']
    except KeyError:
        extra_questions = 1
    ChoiceFormSet = modelformset_factory(Choice, form=AddChoiceForm, extra=extra_questions*4)
    if request.method == "POST":
        formset = ChoiceFormSet(request.POST)
        if formset.is_valid():
            for i in range(0, extra_questions*4):
                choice = Choice(
                test_id = request.session['test_id'],
                question_id = questions_pks[i],

piequiz/viridis/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
{% block head %}{% endblock %}
<title>{% block title %}{% endblock %} &#124; Quizonia</title>
{% load bootstrap3 %}
{% bootstrap_css %}
<meta name="description" content="{% block metadesc %}{% endblock %} Take FREE KCPE past papers online and receive instant results with Quizonia.
You do not need to download anything.">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'viridis/style.css' %}">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
<div id="jumbo-index" class="jumbotron">
  <h1 id="qbrand"><a href="{% url 'viridis:home' %}">Quizonia</a></h1>
  <p>Your Free KCPE Revision Authority</p>
  <p class="row">
    <div class="fb-like col-md-2" data-href="http://www.quizonia.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
    <div class="col-md-4">
      <a class="twitter-follow-button"
       href="https://twitter.com/quizonia"
       data-show-count="false"
       data-lang="en">
        Follow @quizonia
      </a>
      <script>window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));</script>
    </div>
  </p>
</div>
<nav class="navbar navbar-custom" data-spy="affix" data-offset-top="200" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'viridis:home' %}">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      {% if user.is_active and user.is_staff %}
        <li><li><a href="{% url 'viridis:add_test' %}">Create Quiz</a></li>
      {% endif %}
        <li><li><a href="/blog/">Blog</a></li>
      </ul>
      <form id="search" class="navbar-form navbar-left" method="get" action="/search?=">
        <div class="form-group">
          <div class="col-sm-12">
            <div class="left-inner-addon">
              <i class="glyphicon glyphicon-search"></i>
              <input type="search" id="search-input" name="q" class="form-control input-sm" placeholder="Search for KCPE past papers and questions..." />
            </div>
          </div>
      </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            {% if user.is_staff %}
            <li><a href="{% url 'viridis:my_tests' %}">My quizzes</a></li>
            {% endif %}
            <li><a href="{% url 'viridis:profile' %}">Profile</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'django.contrib.auth.views.logout' %}?next={{ request.path }}">Sign out</a></li>
          </ul>
        </li>
        {% else %}
        <a href="/accounts/login/">
          <li>
            <button id="signup" class="btn btn-success navbar-btn btn-sm">Sign up</button>
          </li>
        </a>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div id="wrap">
<noscript>
  <div id="noscript">
    <p><b>Please enable javascript so that this site can play nicely :)</b></p>
  </div>
</noscript>

<div id="main">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
{% block date_created %}
{% endblock %}
{% if user.is_authenticated %}
{% if user.is_active and user.is_staff %}
<hr>
<div class="btn-group">
<button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
  My Quizzes <span class="caret"></span>
</button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="{% url 'viridis:my_tests' %}">View All</a></li>
  </ul>
</div>
{% for user_test in user.test_set.all|slice:":5" %}
  <p><a href="{{ user_test.get_absolute_url }}">{{ user_test.title|truncatechars:45 }}</a></p>
  {% empty %}
    <p>You haven't created any quizzes yet. <a href="{% url 'viridis:add_test' %}">Get to work!</a></p>
{% endfor %}
{% endif %}
<hr>
{% else %}
<hr>
<div id="panel-login" class="panel panel-info">
  <div class="panel-heading"><h1 class=panel-title>Log in</h1></div>
  <div class="panel-body">
    <form class="form-horizontal" method="post" action="{% url 'auth_login' %}" role="form">
    {% csrf_token %}
      <div class="form-group">
        <div class="col-sm-12">
          <div class="left-inner-addon">
            <i class="glyphicon glyphicon-user"></i>
            <input class="form-control" type="text" name="username" placeholder="Username"/>
          </div>
        </div>
      </div>
    <div class="form-group">
      <div class="col-sm-12">
        <div class="left-inner-addon">
          <i class="glyphicon glyphicon-lock"></i>
          <input class="form-control" type="password" name="password" placeholder="Password" />
        </div>
      </div>
    </div>
    <button class="btn btn-success" type="submit"><i class="fa fa-sign-in"></i> Sign in</button>
    <input type="hidden" name="next" value="{{ request.path }}" />
    </form>
</div>
</div>
<hr>
{% endif %}
{% if user.has_usable_password == False %}
<div class="new-password" title="Set a new password">
  <p>Hi {{ user.username }}, you have not set a password yet. Please set one now.</p>
  <form action="{% url 'viridis:password_change' %}" method="post" role="form">
  {% csrf_token %}
    <div class="form-group">
      <input type="password" name="new_password1" class="form-control" placeholder="New Password" autofocus="" />
    </div>
    <div class="form-group">
     <input type="password" name="new_password2" class="form-control" placeholder="Repeat Password"/>
    </div>
     <button class="btn btn-md btn-primary" type="submit">Create Password</button>
   </form>
</div>
{% endif %}
</div>
</div>
{% block footer %}
<footer id="footer-main" class="footer">
  <p><i class="fa fa-info-circle"></i> <a href="/about/">About</a> <i class="fa fa-question-circle"></i> <a href="/faq/">FAQs</a></p>
  <p>&copy; Copyright 2015, Quizonia. All Rights Reserved.</p>
</footer>
{% endblock %}

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <script src="{% static 'viridis/style.js' %}"></script>
</body>
</html>